#!/bin/sh
DEPS_DIR=$(pwd)/macos/deps
mkdir -p $DEPS_DIR/src
pushd $DEPS_DIR/src

#--- USD ---
echo 'Fetching USD'
curl -o usd-18.09.zip -L -C - https://github.com/PixarAnimationStudios/USD/archive/v18.09.zip
unzip -uq usd-18.09.zip
pushd USD-18.09/build_scripts
python build_usd.py --no-python --no-openimageio --build-monolithic -v -v $DEPS_DIR
popd #usd

popd #src
