os: osx
osx_image: xcode9.4
language: swift
xcode_project: macos/usdview.xcodeproj/
xcode_scheme: usdview
xcode_destination: platform=macOS
script: 
    - xcodebuild clean build -project macos/usdview.xcodeproj/ -scheme usdview -destination "platform=macOS" 
