os: osx
osx_image: xcode9.4
language: swift
xcode_project: macos/usdview.xcodeproj/
xcode_scheme: usdview
xcode_destination: platform=macOS
pre_install:
    - brew install cmake

script: 
    - .buildScripts/build-mac-deps
    - .buildScripts/build
    - .buildScripts/test

cache:
  directories:
    - macos/deps
    - $HOME/Library/Caches/Homebrew
